// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { Stimulus } from '../libs/stimulus'


import BarchartController from './barchart_controller'
Stimulus.register('barchart', BarchartController)

import ChartController from './chart_controller'
Stimulus.register('chart', ChartController)

import DatepickerController from './datepicker_controller'
Stimulus.register('datepicker', DatepickerController)

import HelloController from './hello_controller'
Stimulus.register('hello', HelloController)